#include <SDL2/SDL.h>
#include <SDL2/SDL_ttf.h>
#include"core/parent.h"
#include"core/graphics.h"
#include"core/theme.h"
#include"widgets/container.h"
#include"widgets/entry.h"
#include"widgets/drop.h"
#include"widgets/radio.h"
#include"widgets/textbox.h"
#include"widgets/slider.h"
#include"widgets/button.h"
#include"widgets/text.h"
#include"widgets/progress.h"
#include"widgets/image.h"
#include"core/app.h"
